name: CI Pipeline - Build, Deploy, and Test

on:
  workflow_dispatch:
    inputs:
      class_name:
        description: 'Select Test Case to Run'
        required: true
        type: choice
        options:
          - testCases.TC001_Login
          - testCases.Brokenlinks
        default: testCases.TC001_Login

jobs:
  build:
    name: Build Project
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean compile

  deploy:
    name: Deploy Build Artifacts
    runs-on: windows-latest
    needs: build  # ✅ Runs after the build job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simulate Deploy Step
        run: echo "Pretending to deploy application..."

  test:
    name: Run Selenium Tests
    runs-on: windows-latest
    needs: deploy  # ✅ Runs after the deploy job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Restore Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: List testng.xml (for debugging)
        run: dir src\test\resources

      - name: Run Selenium Tests with Maven
        run: mvn clean test "-DsuiteXmlFile=src/test/resources/testng.xml"
        env:
          DISPLAY: :99.0
