name: Run Selenium Tests with Maven

on:
  workflow_dispatch:
    inputs:
      class_name:
        description: 'Select Test Case to Run'
        required: true
        type: choice
        options:
          - testCases.TC001_Login
          - testCases.Brokenlinks
        default: testCases.TC001_Login

jobs:
  test:
    runs-on: windows-latest  # Using Windows environment

    steps:
    # Checkout code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3  # Correct latest version for checking out repo

    # Set up JDK (Java Development Kit)
    - name: Set up JDK 11
      uses: actions/setup-java@v2  # Correct version for setup-java
      with:
        java-version: '11'

    # Install Maven
    - name: Set up Maven
      uses: actions/setup-maven@v2  # Correct version for setup-maven
      with:
        maven-version: '3.8.1'

    # Cache Maven dependencies for faster builds
    - name: Cache Maven dependencies
      uses: actions/cache@v3  # Correct latest version for actions/cache
      with:
        path: C:\Users\runneradmin\.m2\repository  # Path for Maven cache on Windows
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Run tests using Maven, using the selected test class from workflow_dispatch input
    - name: Run Selenium Tests with Maven
      run: mvn clean test -Dtest=${{ github.event.inputs.class_name }}
      env:
        DISPLAY: :99.0  # For X virtual framebuffer (Xvfb) in the CI environment
