name: Run Selenium Tests with Maven

on:
  workflow_dispatch:
    inputs:
      class_name:
        description: 'Select Test Case to Run'
        required: true
        type: choice
        options:
          - testCases.TC001_Login
          - testCases.Brokenlinks
        default: testCases.TC001_Login

jobs:
  test:
    runs-on: windows-latest  # Using Windows environment

    steps:
    # Checkout code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK (Java Development Kit)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # Explicitly specify the distribution

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: C:\Users\runneradmin\.m2\repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Run tests using Maven with the testng.xml
    - name: Run Selenium Tests with Maven
      run: mvn clean test -DsuiteXmlFile=src/test/resources/testng.xml
      env:
        DISPLAY: :99.0  # For X virtual framebuffer (Xvfb) in the CI environment
