name: Run Selenium Tests with Maven

on:
  workflow_dispatch:
    inputs:
      class_name:
        description: 'Select Test Case to Run'
        required: true
        type: choice
        options:
          - testCases.TC001_Login
          - testCases.Brokenlinks
        default: testCases.TC001_Login

jobs:
  test:
    runs-on: windows-latest  # Using Windows environment

    steps:
    # Checkout code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK (Java Development Kit) with the correct distribution
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # Explicitly specify the distribution

    # Install Maven manually from Apache distribution
    - name: Install Maven
      run: |
        # Check if Invoke-WebRequest (PowerShell) is available and download Maven 3.8.1
        try {
          Write-Host "Downloading Apache Maven..."
          Invoke-WebRequest -Uri https://downloads.apache.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.zip -OutFile apache-maven.zip
        } catch {
          Write-Host "Download failed: $_"
          exit 1
        }

        # Extract Maven zip file to C:\apache-maven
        Expand-Archive -Path apache-maven.zip -DestinationPath C:\apache-maven
        # Add Maven to system PATH
        $env:M2_HOME = "C:\apache-maven\apache-maven-3.8.1"
        $env:PATH = "$env:M2_HOME\bin;$env:PATH"
        # Verify Maven version to ensure it’s installed
        mvn -v

    # Cache Maven dependencies for faster builds
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: C:\Users\runneradmin\.m2\repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Run tests using Maven, using the selected test class from workflow_dispatch input
    - name: Run Selenium Tests with Maven
      run: mvn clean test -Dtest=${{ github.event.inputs.class_name }}
      env:
        DISPLAY: :99.0  # For X virtual framebuffer (Xvfb) in the CI environment
