name: Run Selenium Tests with Maven


on:
  workflow_dispatch:
    inputs:
      class_name:
        description: 'Select Test Case to Run'
        required: true
        type: choice
        options:
          - testCases.TC001_Login
          - testCases.Brokenlinks
        default: testCases.TC001_Login

jobs:
  test:
    runs-on: windows-latest  # Using the latest Ubuntu environment

    services:
      # Use the official Selenium Docker image for Chrome and ChromeDriver
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size 2g  # Ensure enough memory for the browser

    steps:
    # Checkout code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up JDK (Java Development Kit)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Install Maven
    - name: Set up Maven
      uses: actions/setup-maven@v2
      with:
        maven-version: '3.8.1'

    # Cache Maven dependencies for faster builds
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Run tests using Maven
    - name: Run Selenium Tests with Maven
      run: mvn clean test -Dtest=testcases.TC001_Login
      env:
        DISPLAY: :99.0  # For X virtual framebuffer (Xvfb) in the CI environment
